<?php
/**
 * Copyright (c) 2019 Kaliop Digital Commerce (https://digitalcommerce.kaliop.com) All Rights Reserved.
 * https://opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 * Kaliop_CatalogGenericProductItem
 * tchausson <tchausson@kaliop.com> <dt@kaliop.com>
 */


/** @var $block Kaliop\CatalogGenericProductItem\Block\ProductList\Item */

use Magento\Framework\App\Action\Action;

$_product = $block->getProduct();
$_product->setDoNotUseCategoryId(true);
$_params = $block->getParams();
$viewMode = is_null($block->getData("viewMode")) ? $_params['viewMode'] : $block->getData("viewMode");
$imageDisplayArea = is_null($block->getData("imageArea")) ? $_params['imageArea'] : $block->getData("imageArea");
$showDescription = is_null($block->getData("showDescription")) ? $_params['showDescription'] : $block->getData("showDescription");
$templateType = is_null($block->getData("templateType")) ? $_params['templateType'] : $block->getData("templateType");
$pos = is_null($block->getData("pos")) ? $_params['pos'] : $block->getData("pos");
$addToBlockHtml = is_null($block->getData("addto")) ? $_params['addto'] : $block->getData("addto");
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_productNameStripped = $block->stripTags($_product->getName(), null, true);
$productImage = $block->getImage($_product, $imageDisplayArea);
if ($pos != null) {
    $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
}
?>

<?php // Product Image ?>
<a href="<?php /* @escapeNotVerified */
echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
    <?php echo $productImage->toHtml(); ?>
</a>

<div class="product details product-item-details">
    <?php // Name ?>
    <strong class="product name product-item-name">
        <a class="product-item-link" href="<?php /* @escapeNotVerified */
        echo $_product->getProductUrl() ?>">
            <h2 class="product-item-title"><?php /* @escapeNotVerified */
                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h2>
        </a>
    </strong>

    <?php // Review ?>
    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

    <?php // Price ?>
    <?php /* @escapeNotVerified */
    echo $block->getProductPrice($_product) ?>

    <div class="product-item-inner">
        <div class="product actions product-item-actions"<?php echo strpos(
            $pos,
            $viewMode . '-actions'
        ) ? $position : ''; ?>>
            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                <?php if ($_product->isSaleable()) : ?>
                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                    echo $postParams['action']; ?>" method="post">
                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                        echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="<?php /* @escapeNotVerified */
                        echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                        echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                        <?php echo $block->getBlockHtml('formkey') ?>
                        <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary">
                            <span><?php /* @escapeNotVerified */
                                echo __('Add to Cart') ?></span>
                        </button>
                    </form>
                <?php else : ?>
                    <?php if ($_product->getIsSalable()) : ?>
                        <div class="stock available">
                            <span><?php /* @escapeNotVerified */
                                echo __('In stock') ?></span>
                        </div>
                    <?php else : ?>
                        <div class="stock unavailable">
                            <span><?php /* @escapeNotVerified */
                                echo __('Out of stock') ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <?php if ($addToBlockHtml): ?>
                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                    <?php echo $addToBlockHtml; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($showDescription) : ?>
            <div class="product description product-item-description">
                <?php /* @escapeNotVerified */
                echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                <a href="<?php /* @escapeNotVerified */
                echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                echo $_productNameStripped ?>" class="action more">
                    <?php /* @escapeNotVerified */
                    echo __('Learn More') ?>
                </a>
            </div>
        <?php endif; ?>
    </div>
</div>